project:
  type: website

website:
  title: "Health Analytics New Zealand"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - bootstrap
      - brand
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto